fix for the invalid application error
Signed-off-by: Dipankar Das <65275144+dipankardas011@users.noreply.github.com>

feat(mock-test): added mongodb external store based storage in mock

Signed-off-by: Dipankar Das <65275144+dipankardas011@users.noreply.github.com>

added the fake flag to the cli

Signed-off-by: Dipankar Das <65275144+dipankardas011@users.noreply.github.com>

fix: mock and cli

Signed-off-by: Dipankar Das <65275144+dipankardas011@users.noreply.github.com>

diff --git a/.github/workflows/test-mock.yml b/.github/workflows/test-mock.yml
--- a/.github/workflows/test-mock.yml
+++ b/.github/workflows/test-mock.yml
@@ -49,105 +49,105 @@ jobs:
       - name: civo create
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe create civo -n demo -r LON1 --nodeSizeMP "g4s.kube.small" --version 1.27.1 --verbose -1 -s local --approve
-          .\ksctl.exe create ha-civo -n ha-demo --nodeSizeDS "fake.small" --version 1.27.1 --nodeSizeLB "fake.small" --nodeSizeCP "fake.small" --nodeSizeWP "fake.small" -s local -r LON1 --verbose -1 --approve
+          .\ksctl.exe create civo -n demo -r LON1 --nodeSizeMP "g4s.kube.small" --version 1.27.1 --verbose -1 -s store-local --approve
+          .\ksctl.exe create ha-civo -n ha-demo --nodeSizeDS "fake.small" --version 1.27.1 --nodeSizeLB "fake.small" --nodeSizeCP "fake.small" --nodeSizeWP "fake.small" -s store-local -r LON1 --verbose -1 --approve
 
       - name: azure create
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe create azure -n demo -r fake --nodeSizeMP "fake" -s local --version 1.27.1 --verbose -1 --approve
-          .\ksctl.exe create ha-azure -n ha-demo --nodeSizeDS "fake"  --version 1.27.1 --nodeSizeLB "fake" --nodeSizeCP "fake" --nodeSizeWP "fake" -r fake --verbose -1 -s local --approve
+          .\ksctl.exe create azure -n demo -r fake --nodeSizeMP "fake" -s store-local --version 1.27.1 --verbose -1 --approve
+          .\ksctl.exe create ha-azure -n ha-demo --nodeSizeDS "fake"  --version 1.27.1 --nodeSizeLB "fake" --nodeSizeCP "fake" --nodeSizeWP "fake" -r fake --verbose -1 -s store-local --approve
 
       - name: aws create
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          # .\ksctl.exe create aws -n demo -r fake --nodeSizeMP "fake" --version 1.27.1 -s local --verbose -1 --approve
-          .\ksctl.exe create ha-aws -n ha-demo --nodeSizeDS "fake"  --version 1.27.1 --nodeSizeLB "fake" --nodeSizeCP "fake" --nodeSizeWP "fake" -r fake --verbose -1 -s local --approve
+          # .\ksctl.exe create aws -n demo -r fake --nodeSizeMP "fake" --version 1.27.1 -s store-local --verbose -1 --approve
+          .\ksctl.exe create ha-aws -n ha-demo --nodeSizeDS "fake"  --version 1.27.1 --nodeSizeLB "fake" --nodeSizeCP "fake" --nodeSizeWP "fake" -r fake --verbose -1 -s store-local --approve
 
       - name: local create
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe create local -n demolocal  --version 1.27.1 --verbose -1 -s local --approve
+          .\ksctl.exe create local -n demolocal  --version 1.27.1 --verbose -1 -s store-local --approve
 
       - name: civo get
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe get -s local -p civo
+          .\ksctl.exe get -s store-local -p civo
 
       - name: azure get
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe get -s local -p azure
+          .\ksctl.exe get -s store-local -p azure
 
       - name: aws get
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe get -s local -p aws
+          .\ksctl.exe get -s store-local -p aws
 
       - name: get all
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe get -s local
+          .\ksctl.exe get -s store-local
 
       - name: civo switch
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe switch -p civo -n demo -s local -r LON1
-          .\ksctl.exe switch -p ha-civo -n ha-demo -s local -r LON1
+          .\ksctl.exe switch -p civo -n demo -s store-local -r LON1
+          .\ksctl.exe switch -p ha-civo -n ha-demo -s store-local -r LON1
 
       - name: aws switch
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          # .\ksctl.exe switch -p aws -n demo -s local -r fake
-          .\ksctl.exe switch -p ha-aws -n ha-demo -s local -r fake
+          # .\ksctl.exe switch -p aws -n demo -s store-local -r fake
+          .\ksctl.exe switch -p ha-aws -n ha-demo -s store-local -r fake
 
       - name: azure switch
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe switch -p azure -n demo -s local -r fake
-          .\ksctl.exe switch -p ha-azure -n ha-demo -s local -r fake
+          .\ksctl.exe switch -p azure -n demo -s store-local -r fake
+          .\ksctl.exe switch -p ha-azure -n ha-demo -s store-local -r fake
 
       - name: civo scale up and down
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe delete ha-civo del-nodes -n ha-demo --noWP 0 -r LON1 -s local --approve -v -1
-          .\ksctl.exe create ha-civo add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake.small" -s local -r LON1 -v -1 --approve
+          .\ksctl.exe delete ha-civo del-nodes -n ha-demo --noWP 0 -r LON1 -s store-local --approve -v -1
+          .\ksctl.exe create ha-civo add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake.small" -s store-local -r LON1 -v -1 --approve
 
       - name: azure scale up and down
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe delete ha-azure del-nodes -n ha-demo --noWP 0 -r fake -s local --approve -v -1
-          .\ksctl.exe create ha-azure add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake" -s local -r fake -v -1 --approve
+          .\ksctl.exe delete ha-azure del-nodes -n ha-demo --noWP 0 -r fake -s store-local --approve -v -1
+          .\ksctl.exe create ha-azure add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake" -s store-local -r fake -v -1 --approve
 
       - name: aws scale up and down
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe delete ha-aws del-nodes -n ha-demo --noWP 0 -r fake -s local --approve -v -1
-          .\ksctl.exe create ha-aws add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake" -s local -r fake -v -1 --approve
+          .\ksctl.exe delete ha-aws del-nodes -n ha-demo --noWP 0 -r fake -s store-local --approve -v -1
+          .\ksctl.exe create ha-aws add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake" -s store-local -r fake -v -1 --approve
 
       - name: civo delete
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe delete civo -n demo -r LON1 -s local -v -1 --approve
-          .\ksctl.exe delete ha-civo -n ha-demo -r LON1 -s local -v -1 --approve
+          .\ksctl.exe delete civo -n demo -r LON1 -s store-local -v -1 --approve
+          .\ksctl.exe delete ha-civo -n ha-demo -r LON1 -s store-local -v -1 --approve
 
 
       - name: azure delete
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe delete azure -n demo -r fake -s local -v -1 --approve
-          .\ksctl.exe delete ha-azure -n ha-demo -r fake -s local -v -1 --approve
+          .\ksctl.exe delete azure -n demo -r fake -s store-local -v -1 --approve
+          .\ksctl.exe delete ha-azure -n ha-demo -r fake -s store-local -v -1 --approve
 
       - name: aws delete
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          # .\ksctl.exe delete aws -n demo -r fake -s local -v -1 --approve
-          .\ksctl.exe delete ha-aws -n ha-demo -r fake -s local -v -1 --approve
+          # .\ksctl.exe delete aws -n demo -r fake -s store-local -v -1 --approve
+          .\ksctl.exe delete ha-aws -n ha-demo -r fake -s store-local -v -1 --approve
 
       - name: local delete
         working-directory: 'C:\Users\runneradmin\AppData\Local\ksctl'
         run: |
-          .\ksctl.exe delete local -n demolocal -s local -v -1 --approve
+          .\ksctl.exe delete local -n demolocal -s store-local -v -1 --approve
 
   ksctl-cli-unix:
     strategy:
@@ -192,108 +192,160 @@ jobs:
       - name: civo create
         run: |
           set -xe
-          ksctl create civo -n demo -r LON1 --nodeSizeMP "g4s.kube.small"  --version 1.27.1 -s local --verbose -1 --approve
-          ksctl create ha-civo -n ha-demo --nodeSizeDS "fake.small" -s local  --version 1.27.1 --nodeSizeLB "fake.small" --nodeSizeCP "fake.small" --nodeSizeWP "fake.small" -r LON1 --verbose -1 --approve
+          ksctl create civo -n demo -r LON1 --nodeSizeMP "g4s.kube.small"  --version 1.27.1 -s store-local --verbose -1 --approve
+          ksctl create ha-civo -n ha-demo --nodeSizeDS "fake.small" -s store-local  --version 1.27.1 --nodeSizeLB "fake.small" --nodeSizeCP "fake.small" --nodeSizeWP "fake.small" -r LON1 --verbose -1 --approve
 
       - name: azure create
         run: |
           set -xe
-          ksctl create azure -n demo -r fake --nodeSizeMP "fake" -s local  --version 1.27.1 --verbose -1 --approve
-          ksctl create ha-azure -n ha-demo --nodeSizeDS "fake" -s local --nodeSizeLB "fake"  --version 1.27.1 --nodeSizeCP "fake" --nodeSizeWP "fake" -r fake --verbose -1 --approve
+          ksctl create azure -n demo -r fake --nodeSizeMP "fake" -s store-local  --version 1.27.1 --verbose -1 --approve
+          ksctl create ha-azure -n ha-demo --nodeSizeDS "fake" -s store-local --nodeSizeLB "fake"  --version 1.27.1 --nodeSizeCP "fake" --nodeSizeWP "fake" -r fake --verbose -1 --approve
 
       - name: aws create
         run: |
           set -xe
-          # ksctl create aws -n demo -r fake --nodeSizeMP "fake" -s local  --version 1.27.1 --verbose -1 --approve
-          ksctl create ha-aws -n ha-demo --nodeSizeDS "fake" -s local --nodeSizeLB "fake" --version 1.27.1  --nodeSizeCP "fake" --nodeSizeWP "fake" -r fake --verbose -1 --approve
+          # ksctl create aws -n demo -r fake --nodeSizeMP "fake" -s store-local  --version 1.27.1 --verbose -1 --approve
+          ksctl create ha-aws -n ha-demo --nodeSizeDS "fake" -s store-local --nodeSizeLB "fake" --version 1.27.1  --nodeSizeCP "fake" --nodeSizeWP "fake" -r fake --verbose -1 --approve
 
       - name: local create
         run: |
           set -xe
-          ksctl create local -n demolocal -s local --verbose -1 --approve
+          ksctl create local -n demolocal -s store-local --verbose -1 --approve
+
+      - name: local create mongodb
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        run: |
+          set -xe
+          unset KSCTL_FAKE_FLAG_ENABLED
+          docker run -d \
+            --name mongodb \
+            -p 27017:27017 \
+            -e MONGO_INITDB_ROOT_USERNAME=root \
+            -e MONGO_INITDB_ROOT_PASSWORD=1234 \
+            mongo
+          export MONGODB_URI="mongodb://root:1234@127.0.0.1:27017"
+          ksctl create local -n demolocal-extmongo -s external-store-mongodb --verbose -1 --approve
 
       - name: civo get
         run: |
           set -xe
-          ksctl get -p civo -s local
+          ksctl get -p civo -s store-local
 
       - name: azure get
         run: |
           set -xe
-          ksctl get -p azure -s local
+          ksctl get -p azure -s store-local
 
       - name: aws get
         run: |
           set -xe
-          ksctl get -p aws -s local
+          ksctl get -p aws -s store-local
+
+      - name: local get
+        run: |
+          set -xe
+          ksctl get -p local -s store-local
+
+      - name: local get mongo
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        run: |
+          set -xe
+          unset KSCTL_FAKE_FLAG_ENABLED
+          ksctl get -p local -s external-store-mongodb
 
       - name: all
         run: |
           set -xe
-          ksctl get -s local
+          ksctl get -s store-local
+      
+      - name: all mongodb
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        run: |
+          set -xe
+          unset KSCTL_FAKE_FLAG_ENABLED
+          ksctl get -s external-store-mongodb
+
+      - name: local switch
+        run: |
+          set -xe
+          ksctl switch -p local -n demolocal -s store-local
+
+      - name: local switch mongodb
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        run: |
+          set -xe
+          unset KSCTL_FAKE_FLAG_ENABLED
+          ksctl switch -p local -n demolocal-extmongo -s external-store-mongodb
 
       - name: civo switch
         run: |
           set -xe
-          ksctl switch -p civo -n demo -s local -r LON1
-          ksctl switch -p ha-civo -n ha-demo -s local -r LON1
+          ksctl switch -p civo -n demo -s store-local -r LON1
+          ksctl switch -p ha-civo -n ha-demo -s store-local -r LON1
 
       - name: azure switch
         run: |
           set -xe
-          ksctl switch -p azure -n demo -s local -r fake
-          ksctl switch -p ha-azure -n ha-demo -s local -r fake
+          ksctl switch -p azure -n demo -s store-local -r fake
+          ksctl switch -p ha-azure -n ha-demo -s store-local -r fake
 
       - name: aws switch
         run: |
           set -xe
-          # ksctl switch -p aws -n demo -s local -r fake
-          ksctl switch -p ha-aws -n ha-demo -s local -r fake
+          # ksctl switch -p aws -n demo -s store-local -r fake
+          ksctl switch -p ha-aws -n ha-demo -s store-local -r fake
 
       - name: civo scale up and down
         run: |
           set -xe
-          ksctl delete ha-civo del-nodes -n ha-demo --noWP 0 -r LON1 -s local --approve -v -1
-          ksctl create ha-civo add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake.small" -s local -r LON1 -v -1 --approve
+          ksctl delete ha-civo del-nodes -n ha-demo --noWP 0 -r LON1 -s store-local --approve -v -1
+          ksctl create ha-civo add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake.small" -s store-local -r LON1 -v -1 --approve
 
       - name: azure scale up and down
         run: |
           set -xe
-          ksctl delete ha-azure del-nodes -n ha-demo --noWP 0 -s local -r fake --approve -v -1
-          ksctl create ha-azure add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake" -s local -r fake -v -1 --approve
+          ksctl delete ha-azure del-nodes -n ha-demo --noWP 0 -s store-local -r fake --approve -v -1
+          ksctl create ha-azure add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake" -s store-local -r fake -v -1 --approve
 
       - name: aws scale up and down
         run: |
           set -xe
-          ksctl delete ha-aws del-nodes -n ha-demo --noWP 0 -s local -r fake --approve -v -1
-          ksctl create ha-aws add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake" -s local -r fake -v -1 --approve
+          ksctl delete ha-aws del-nodes -n ha-demo --noWP 0 -s store-local -r fake --approve -v -1
+          ksctl create ha-aws add-nodes -n ha-demo --noWP 1  --version 1.27.1 --nodeSizeWP "fake" -s store-local -r fake -v -1 --approve
 
       - name: civo delete
         run: |
           set -xe
-          ksctl delete civo -n demo -r LON1 -s local -v -1 --approve
-          ksctl delete ha-civo -n ha-demo -r LON1 -s local -v -1 --approve
+          ksctl delete civo -n demo -r LON1 -s store-local -v -1 --approve
+          ksctl delete ha-civo -n ha-demo -r LON1 -s store-local -v -1 --approve
 
       - name: azure delete
         run: |
           set -xe
-          ksctl delete azure -n demo -r fake -s local -v -1 --approve
-          ksctl delete ha-azure -n ha-demo -r fake -s local -v -1 --approve
+          ksctl delete azure -n demo -r fake -s store-local -v -1 --approve
+          ksctl delete ha-azure -n ha-demo -r fake -s store-local -v -1 --approve
 
       - name: aws delete
         run: |
           set -xe
-          # ksctl delete aws -n demo -r fake -s local -v -1 --approve
-          ksctl delete ha-aws -n ha-demo -r fake -s local -v -1 --approve
+          # ksctl delete aws -n demo -r fake -s store-local -v -1 --approve
+          ksctl delete ha-aws -n ha-demo -r fake -s store-local -v -1 --approve
 
       - name: local delete
         run: |
           set -xe
-          ksctl delete local -n demolocal -v -1 -s local --approve
+          ksctl delete local -n demolocal -v -1 -s store-local --approve
+
+      - name: local delete mongodb
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        run: |
+          set -xe
+          unset KSCTL_FAKE_FLAG_ENABLED
+          ksctl delete local -n demolocal-extmongo -v -1 -s external-store-mongodb --approve
 
       - name: storage provider
         run: |
           set -xe
-          ksctl create local -n demolocal -s local -v -1 --approve
-          ksctl create local -n demolocal -s external-mongo -v -1 --approve || echo "Expected to fail :) due to missing env vars"
-          ksctl create local -n demolocal -s local123 -v -1 --approve || echo "Expected to fail :) due to invalid provider name"
+          ksctl create local -n demolocal -s store-local -v -1 --approve
+          ksctl create local -n demolocal -s external-store-mongodb -v -1 --approve || echo "Expected to fail :) due to missing env vars"
+          ksctl create local -n demolocal -s store-local123 -v -1 --approve || echo "Expected to fail :) due to invalid provider name"
